repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix]
        exclude: '\.ipynb$'
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --filter-files]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [--count, --show-source, --statistics, '--ignore', 'E203,E501,W503']
        log_file: flake8.log

  # Optional: If you're not using `setup.cfg`, you can remove this
  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v2.5.0
  #   hooks:
  #     - id: setup-cfg-fmt

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        args: ["--rcfile=.pylintrc", "--init-hook=import sys; sys.path.insert(0, 'agents')", "--disable=invalid-name,global-statement,global-variable-not-assigned,not-callable,broad-exception-caught"]
        language: python
        types: [python]
        require_serial: true
        files: ^agents/.*\.py$
